### ISSUE TITLE
用户邀请

### ISSUE THREAD

**Issue by kingdido999** [bloc42/news#31]
有两种不同的用户邀请设计方案：

#### 优点：
- 集中控制所有的邀请名额（同时也可能是缺点）。

#### 缺点：
- 整个流程步骤较多，用户体验不佳。
- 需要人工管理邀请码。比如需要记录邀请码是否已给到别人，否则可能会把同样的邀请码给到多个用户。
- 对后期的开放式注册并没有起到收集高质量用户的作用。

#### 优点：
- 用户体验好。新用户点击邮件中的链接就能进行注册。
- 更灵活，不需要手动管理邀请码。
- 可以利用初期的优质用户给我们后期带来更多优质的用户。

#### 缺点：
- 不能够集中控制邀请名额。

我个人更倾向于第二种方案。

**Comment by kingdido999** [comment]
@tyr034 @summerhack 你们觉得呢？

**Comment by tyr034** [comment]
我觉得第一中的确不够scable，然后也比较难以管理？
而且的确论坛需要活跃度，所以我觉得第二种方式比较好吧
关于第二种做法，我想知道更多的细节？

比如最开始的一批用户是怎么注册呢？
还是邀请码吗？

然后注册成功之后，他们就可以再去邀请别人？
这个你觉得需要限制他们的邀请人数吗？

**Comment by kingdido999** [comment]
第一个用户可以直接在数据库里创建，然后就可以开始邀请其他人。具体的邀请就是用户填写邮箱，点击邀请后发送邮件，被邀请者打开邮件中的链接后跳转到注册页面，完成注册就行。整个流程对于用户来说是没有邀请码的概念的。

因为我们都是会邀请自己比较熟悉的人，不会存在让spammer拿到邀请的机会，限制邀请人数并没有什么意义，所以就不做限制吧。

**Comment by tyr034** [comment]
我觉得ok 吧

**Comment by summerhack** [comment]
邮件中的链接要带上一串单次有效的邀请码，用户注册后依然会有邮箱验证环节，大概是这样？

**Comment by kingdido999** [comment]
@summerhack 对的
